services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=taskdb'
      - 'POSTGRES_PASSWORD=niyo'
      - 'POSTGRES_USER=niyo'
    ports:
      - '5400:5432'
    volumes:
          - postgres_data:/var/lib/postgresql/data
# FAILING ON MY MAC, PERHAPS NODE VERSION WOULD LOOK AT IT LATER
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: simple-task-mgt
#    restart: unless-stopped
#    ports:
#      - "5000:5000"
#    environment:
#      - NODE_ENV=production
#      - DB_TYPE=${DB_TYPE}
#      - DB_HOST=${DB_HOST}
#      - DB_PORT=${DB_PORT}
#      - DB_USERNAME=${DB_USERNAME}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_DATABASE=${DB_DATABASE}
#      - AUTO_LOAD_ENTITIES=${AUTO_LOAD_ENTITIES}
#      - SYNCHRONIZE=${SYNCHRONIZE}
##    networks:
##      - nest
#    depends_on:
#        - postgres
volumes:
          postgres_data:

